name: Unit Tests

on:
  pull_request: null
  push:
    branches:
      - master
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-versions: ['8.0', '8.1', '8.2']
        actions:
          -
            name: 'Unit Tests'
            run: composer check-cs

    name: PHP ${{ matrix.php-versions }} Tests

    steps:
      -   uses: actions/checkout@v2

      # see https://github.com/shivammathur/setup-php
      -   uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php-versions }}
            coverage: none

      # composer install cache - https://github.com/ramsey/composer-install
      -   uses: "ramsey/composer-install@v1"

      -   run: ${{ matrix.actions.run }}